import{CHANCES,HERBS,POISONS,type Token}from"./data";
export type Phase="alchemy"|"chance"|"settlement"|"market"|"gameover";
export type Player={id:number;name:string;bag:Token[];drawn:Token[];cultivation:number;spiritStones:number;crystals:number;lotus:number;startPosition:number;position:number;poison:number;exploded:boolean;done:boolean;finalScore?:number};
export type GameState={round:number;phase:Phase;activePlayer:number;players:Player[];currentChance?:typeof CHANCES[number];lastRoll?:{die:number;result:"success"|"safe"|"failure";label:string;text:string};message:string;log:string[]};
const clone=(g:GameState):GameState=>structuredClone(g);const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
export function createGame(count:number):GameState{return{round:1,phase:"alchemy",activePlayer:0,players:Array.from({length:count},(_,i)=>({id:i+1,name:`修士 ${i+1}`,bag:[...POISONS,HERBS[0],HERBS[3]],drawn:[],cultivation:0,spiritStones:0,crystals:0,lotus:1,startPosition:0,position:0,poison:0,exploded:false,done:false})),message:"丹爐已熱，決定何時停手。",log:["仙途開啟：第一回合煉丹開始。"]}}
export function drawToken(input:GameState){const g=clone(input),p=g.players[g.activePlayer];if(p.done||p.exploded||!p.bag.length)return g;const index=Math.floor(Math.random()*p.bag.length),t=p.bag.splice(index,1)[0];p.drawn.push(t);p.position+=t.steps;if(t.kind==="poison")p.poison+=t.steps;else{p.cultivation+=t.bonusCultivation??0;p.spiritStones+=t.bonusStones??0;p.crystals+=t.bonusCrystals??0}g.message=`抽到「${t.name}」，丹爐前進 ${t.steps} 步。`;g.log.unshift(`${p.name}抽到${t.name}。`);if(p.poison>7){p.exploded=true;p.done=true;g.message="丹毒超過 7，炸爐！";g.log.unshift(`${p.name}炸爐了！`)}return p.done?advance(g):g}
function advance(g:GameState){const next=g.players.findIndex((p,i)=>i>g.activePlayer&&!p.done);if(next>=0){g.activePlayer=next;if(g.phase==="chance"){g.currentChance=pick(CHANCES);g.lastRoll=undefined}return g}g.players.forEach(p=>p.done=false);g.activePlayer=0;if(g.phase==="alchemy"){g.phase="chance";g.currentChance=pick(CHANCES);g.lastRoll=undefined;g.message="機緣已至，擲骰判命。"}else if(g.phase==="chance"){g.phase="settlement";g.currentChance=undefined;g.lastRoll=undefined;g.message="依丹爐格位領取成果。"}else if(g.phase==="settlement"){g.phase="market";g.message="消耗本回合靈石購買藥材。"}else if(g.phase==="market"){if(g.round===9)return finish(g);g.round++;g.phase="alchemy";g.players.forEach(p=>{p.spiritStones=0;p.position=0;p.poison=0;p.exploded=false;p.bag.push(...p.drawn);p.drawn=[]});g.message="新一回合，丹爐再啟。"}return g}
export function nextTurn(input:GameState,reason:string){const g=clone(input),p=g.players[g.activePlayer];p.done=true;g.log.unshift(`${p.name}${reason==="stop"?"選擇收手":"完成本階段"}。`);return advance(g)}
export function rollChance(input:GameState){const g=clone(input),p=g.players[g.activePlayer];if(!g.currentChance||g.lastRoll)return g;const die=Math.ceil(Math.random()*6),result=die>=5?"success":die>=3?"safe":"failure",label=result==="success"?"成功":result==="safe"?"平安":"失敗",text=g.currentChance[result];g.lastRoll={die,result,label,text};applySimple(p,text,result);g.log.unshift(`${p.name}擲出 ${die}：${label}。`);return g}
function applySimple(p:Player,text:string,result:string){if(result==="safe")return;const raw=text.match(/[+-]\d/)?.[0];const n=raw?Math.abs(Number(raw)):1;if(text.includes("修為"))p.cultivation=Math.max(0,p.cultivation+(text.includes("-")?-n:n));if(text.includes("靈石"))p.spiritStones=Math.max(0,p.spiritStones+(text.includes("-")?-n:n));if(text.includes("晶石"))p.crystals+=1;if(text.includes("冰魄蓮"))p.lotus+=1;if(text.includes("起始格"))p.startPosition+=1;if(text.includes("丹毒（1步）"))p.bag.push(POISONS[0]);if(text.includes("丹毒（2步）"))p.bag.push(POISONS[4]);if(text.includes("獲得下品聚靈草"))p.bag.push(HERBS[0]);if(text.includes("下品黃精參")&&text.includes("獲得"))p.bag.push(HERBS[3])}
export function settlePlayer(input:GameState,choice:"all"|"cultivation"|"stones"){const g=clone(input),p=g.players[g.activePlayer],pos=p.position+p.startPosition,c=Math.floor(pos/4),s=2+Math.floor(pos/3),x=pos>=8?1:0;if(choice==="all"||choice==="cultivation")p.cultivation+=c;if(choice==="all"||choice==="stones")p.spiritStones+=s;p.crystals+=x;p.done=true;g.log.unshift(`${p.name}完成結算。`);return advance(g)}
export function buyHerb(input:GameState,id:string){const g=clone(input),p=g.players[g.activePlayer],h=HERBS.find(x=>x.id===id);if(!h||h.price>p.spiritStones)return g;p.spiritStones-=h.price;p.bag.push(h);g.message=`購入${h.grade}${h.name}，已放入乾坤袋。`;g.log.unshift(`${p.name}購入${h.grade}${h.name}。`);return g}
function finish(g:GameState){g.phase="gameover";g.players=g.players.map(p=>{const all=[...p.bag,...p.drawn];return{...p,bag:all,drawn:[],finalScore:p.cultivation+p.crystals+all.filter(t=>t.kind==="herb"&&t.grade!=="下品").length-all.filter(t=>t.kind==="poison").length}}).sort((a,b)=>(b.finalScore??0)-(a.finalScore??0));g.message="九回合已畢，仙途有主。";return g}
